[package]
name = "amber-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.1", features = ["full"] }
tower-lsp = "0.20.0"
phf = { version = "0.11", features = ["macros"] }
dashmap = "6.0.1"
ropey = "1.6.1"
chumsky = "0.9.3"

[dev-dependencies]
insta = { version = "1.39.0", features = ["yaml"] }
