name: Quality Check
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          override-with-toolchain: true

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: rust-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-${{ runner.os }}-cargo-

      - name: Install dependencies
        run: cargo install --path .

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run tests
        run: cargo test --all-features --verbose